add a verification step to check if the table and the column are created

diff --git a/.github/workflows/snowflake-devops-demo.yml b/.github/workflows/snowflake-devops-demo.yml
--- a/.github/workflows/snowflake-devops-demo.yml
+++ b/.github/workflows/snowflake-devops-demo.yml
@@ -38,6 +38,29 @@ jobs:
           python --version
           echo "Step 1: Installing schemachange"
           pip install schemachange
+          pip install snowflake-cli-labs
           
           echo "Step 2: Running schemachange"
           schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
+
+
+      # Step 4: Verification step - Execute verification script
+      - name: Verify Schema Changes
+        env:
+          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
+          SF_USERNAME: ${{ secrets.SF_USERNAME }}
+          SF_ROLE: ${{ secrets.SF_ROLE }}
+          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
+          SF_DATABASE: ${{ secrets.SF_DATABASE }}
+          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
+        run: |
+          echo "Step 3: Executing verification script"
+          snowsql -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -f $GITHUB_WORKSPACE/verify/script.sql
+          VERIFY_RESULT=$?
+          
+          # Check if verification succeeded
+          if [ $VERIFY_RESULT -ne 0 ]; then
+            echo "Verification failed. Rolling back..."
+            exit 1  # Exit with failure to trigger rollback
+          fi
+          echo "Schema changes verified successfully."
